### ISSUE TITLE
emergency suspension reserve supply privilege for deployer 

### ISSUE THREAD

**Issue by cosmosinscription** [jdogresorg/Broadcast-Token-Naming-System#23]
Community developers and participants have recently had a strong controversy over the token deployer's privilege of reserving tokens, and I feel that we need to take immediate and urgent steps to keep `DEPLOY`  Action ，the token asset issuance process more neat and fair and try our best to gain the trust of users, especially BTNS still in cold start stage,so we have to be especially careful about fairness and taking care of the player's feelings

Format active now
**Broadcast Format:** 
`bt:DEPLOY|TICK|MAX_SUPPLY|MAX_MINT|DECIMALS|ICON|MINT_SUPPLY|TRANSFER|TRANSFER_SUPPLY`

Format need to adjust to :
**Broadcast Format:** 
`bt:DEPLOY|TICK|MAX_SUPPLY|MAX_MINT|DECIMALS|ICON|MINT_SUPPLY`

 BTNS NEW `DEPLOY` commands and the `ACTIVATION_BLOCK` : 
- `DEPLOY` - TBD

for **DEPLOY**  Action Deployer will no longer with the right to transfer some initianl supply to specific address 
for **ISSUE** Action no change. maintain  flexibility in the asset issuance process and specific production scenarios

**Comment by jdogresorg** [comment]
My thoughts behind the current token reservation system are discussed in my [BTNS Token Reservations ](https://github.com/jdogresorg/Broadcast-Token-Naming-System/discussions/8) post

Thank you for the feedback. However, I will not be removing features from the BTNS indexer and forcing all tokens to one distribution method at this time. I am of the belief that having more functionality and options in a platform is better for experimentation, so I am going to build the BTNS platform features how I best see fit.

Any user who has concern about how a specific token's supply came in to existence, can easily investigate in the block explorer and see exactly how the token was minted. 

The BTNS Spec is open source, as is the indexer... your free to take the code and do whatever you would like with it in your own version.... in fact, the project is purposely built so that it is pretty trivial for someone to roll out their own version/ledger.

All that would be needed for you to roll your own ledger is for you to : 

1. Have your users start broadcasting with a new prefix instead of `bt:` like `xt:`
    -  ex `xt:DEPLOY|TICK|MAX_SUPPLY|MAX_MINT|DECIMALS|ICON|MINT_SUPPLY`
2. Setup counterparty fednode
    - https://docs.counterparty.io/docs/advanced/federated-node/getting-started/
3. Setup counterparty2mysql
    -  https://github.com/jdogresorg/counterparty2mysql
4. Fork BTNS indexer code to start parsing txs with your 
    - https://github.com/jdogresorg/Broadcast-Token-Naming-System/tree/master/indexer
5. Setup / Build a block explorer similar to btns.xchain.io so users can see what is happening with the tokens they mint on your ledger.
